name: Deploy - Run after successful merge to main

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - merged
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true

    - name: Deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        gem install kamal
        KAMAL_REGISTRY_PASSWORD="something" kamal deploy
