name: Deploy - Run after successful merge to main

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - merged
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: gem install kamal
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: |
          KAMAL_REGISTRY_PASSWORD="something" kamal deploy
